### ISSUE TITLE
Kind.slx and CocosimSpecification.slx

### ISSUE THREAD

**Issue by hbourbouh** [coco-team/cocoSim2#3]
Why there are two files with the same content.
I found that Kind.sls is the one used by Validator callback, so any modification to CocosimSpecification will not impact the callback.
Can we have one and remove Kind.slx from contract_callback.m (lines 180) and use CocosimSpecification.slx?

Thanks,

**Comment by mudathirmahgoub** [comment]
Thanks for noticing that. I missed to update the contract_callback to use the new Library. Kind.slx is still needed for contract examples.
