### ISSUE TITLE
OuterTransitions in chart_struct

### ISSUE THREAD

**Issue by hbourbouh** [coco-team/cocoSim2#6]
I am wondering why the OuterTransitions in Junction is encapsulated in "Destination":
**transitionStruct.Destination** = buildDestinationStruct(transitions(i));
junctionStruct.OuterTransitions = [junctionStruct.OuterTransitions transitionStruct];

But in State is not:
**transitionStruct** = buildDestinationStruct(transitions(i));                       
stateStruct.OuterTransitions = [stateStruct.OuterTransitions transitionStruct];

Could you please remove Destination from transitionStruct in junction case, that will make more sense to have a common grammar for all OuterTransitions.

I wanted to make the modification but it may break Paul translator of Stateflow. So you need to adapt his code to access directly the OuterTransitions struct without going throw Destination.
BTW there is another Destination field in OuterTransition struct, this one is correct.

Thanks,
Hamza

**Comment by mudathirmahgoub** [comment]
The junction version is a mistake. It should be just like states
**transitionStruct** = buildDestinationStruct(transitions(i));
